name: Build LaTeX document
on:
  push:
    branches: 
      - main
jobs:
  build_latex:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - name: Install LaTeX
        run: brew cask install mactex-no-gui && eval "$(/usr/libexec/path_helper)"
      - name: Compile tex file
        run: /Library/TeX/texbin/xelatex -interaction nonstopmode template_cn_blue.tex
